# Generated by Django 3.2.9 on 2021-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uutoken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
