# Generated by Django 3.2.9 on 2021-12-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='balance',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
