# Generated by Django 3.2.9 on 2021-12-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_expense_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
    ]
