# Generated by Django 3.2.9 on 2021-12-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
