# Generated by Django 3.2.9 on 2021-12-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_expense_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='balance',
        ),
    ]
