# Generated by Django 3.2.9 on 2021-12-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_remove_expense_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
