# Generated by Django 3.2.9 on 2022-02-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_expense_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='xyz',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
