# Generated by Django 3.2.9 on 2022-02-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_expense_xyz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='xyz',
        ),
    ]
